### ISSUE TITLE
KeyError: "Unable to open object (object 'train_data_full' doesn't exist)"

### ISSUE THREAD

**Issue by Imagicguy** [leftthomas/ImageDeblurring#14] opened 2018-03-03 11:56 UTC
I finished all the prerequisites ,but when I typed "python main.py" in the cmd ,the error happened.

Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 104, in <module>
    train(batch_size=2, epoch_num=10)
  File "main.py", line 13, in train
    y_train, x_train = data_utils.load_data(data_type='train')
  File "C:\Users\wuhaili8221308\Desktop\毕设\毕设文献\code\ImageDeblurring-master\data_utils.py", line 60, in load_data
    data_full = f['%s_data_full' % data_type][:].astype(np.float32)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "C:\Users\wuhaili8221308\Anaconda3\lib\site-packages\h5py\_hl\group.py", line 167, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py\_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py\_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py\h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'train_data_full' doesn't exist)"

**Comment by leftthomas** [comment] 2018-03-03 13:35
#13

**Comment by leftthomas** [comment] 2018-03-03 13:35
Duplicate of #13

**Closed as completed by leftthomas** 2018-03-03 13:35 UTC
